-- MySQL Script generated by MySQL Workbench
-- 10/15/15 10:49:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancog8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancog8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancog8` DEFAULT CHARACTER SET latin1 ;
 
USE `bancog8` ;

-- -----------------------------------------------------
-- Table `bancog8`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancog8`.`prestamo` (
  `id_prestamo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  `apellido` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `montoQ` DECIMAL(10,2) NOT NULL,
  `saldo_actual` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_prestamo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bancog8`.`abonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancog8`.`abonos` (
  `id_abono` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(50) NULL DEFAULT NULL,
  `montoQ` DECIMAL(10,2) NULL DEFAULT NULL,
  `montoD` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_prestamo` INT(11) NOT NULL,
  `id_remesadora` INT(11) NOT NULL DEFAULT '0',
  `id_remesa` INT(11) NOT NULL,
  `nombre_emisor` VARCHAR(100) NULL DEFAULT NULL,
  `nombre_receptor` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_abono`),
  INDEX `id_prestamo` (`id_prestamo` ASC),
  CONSTRAINT `abonos_ibfk_1`
    FOREIGN KEY (`id_prestamo`)
    REFERENCES `bancog8`.`prestamo` (`id_prestamo`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bancog8`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancog8`.`cuenta` (
  `id_cuenta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  `apellido` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cuenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bancog8`.`remesas_efectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancog8`.`remesas_efectivo` (
  `id_remesa` INT(11) NOT NULL,
  `id_remesadora` INT(11) NOT NULL DEFAULT '0',
  `fecha` VARCHAR(50) NULL DEFAULT NULL,
  `nombre_emisor` VARCHAR(100) NULL DEFAULT NULL,
  `nombre_receptor` VARCHAR(100) NULL DEFAULT NULL,
  `montoQ` DECIMAL(10,2) NULL DEFAULT NULL,
  `montoD` DECIMAL(10,2) NULL DEFAULT NULL,
  `estado` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id_remesa`, `id_remesadora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bancog8`.`tipo_cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancog8`.`tipo_cambio` (
  `cambioCompra` DECIMAL(10,2) NULL DEFAULT NULL,
  `cambioVenta` DECIMAL(10,2) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bancog8`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancog8`.`transaccion` (
  `id_transaccion` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(50) NULL DEFAULT NULL,
  `montoQ` DECIMAL(10,2) NULL DEFAULT NULL,
  `montoD` DECIMAL(10,2) NULL DEFAULT NULL,  
  `id_cuenta` INT(11) NULL DEFAULT NULL,
  `id_remesadora` INT(11) NOT NULL DEFAULT '0',
  `id_remesa` INT(11) NOT NULL,
  `nombre_emisor` VARCHAR(100) NULL DEFAULT NULL,
  `nombre_receptor` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX `id_cuenta` (`id_cuenta` ASC),
  CONSTRAINT `transaccion_ibfk_1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `bancog8`.`cuenta` (`id_cuenta`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


